openapi: '3.0.2'
info:
  title: Configuration Service
  description: This is a configuration service, providing settings for the application to work
  version: '1.0.0'
  
servers:
  - url: https://localhost/configuration/v1
    description: localhost

paths:
  /{section}:
    get:
      tags:
        - config
      description: Get configuration for given section
      operationId: controllers.configuration_controller.get_section
      parameters:
        - in: path
          name: section
          description: Give section name
          required: true
          schema:
            type: string
          example: features
        - in: header
          name: 'entity'
          description: Company name
          required: false
          schema: 
            type: string
          example: default
        - in: header
          name: 'accept_language'
          description: Language code
          required: false
          schema:
            type: string
          example: en-in
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object  
        '204':
          description: No Content
  /{section}/{key}:
    get:
      tags:
        - config
      description: Get configuration for given section and key
      operationId: controllers.configuration_controller.get_section_key
      parameters:
        - in: path
          name: section
          description: Give section name
          required: true
          schema:
            type: string
          example: 'features'
        - in: path
          name: key
          description: Give key name
          required: true
          schema:
            type: string
          example: 'basic'
        - in: header
          name: 'entity'
          description: Company name
          required: false
          schema: 
            type: string
          example: default
        - in: header
          name: 'accept_language'
          description: Language code
          required: false
          schema:
            type: string
          example: en_in
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object  
        '204':
          description: No Content

