openapi: '3.0.2'
info:
  title: REST Starter Kit
  description: This is a starter kit that can be used to create microservice
  version: '1.0.0'
  
servers:
  - url: https://localhost/starterkit/v1
    description: localhost

paths:
  /greetings/{word}:
    get:
      tags:
        - greetings
      description: Get information about the given word
      operationId: controllers.word_controller.get_word
      parameters:
        - in: path
          name: word
          description: Give me some word, I want to learn
          required: true
          schema:
            type: string
          example: 'One'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/word-message'
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/word-message'
components:
  schemas:
    word-message:
      type: object
      properties:
        input:
          type: string
          description: Word entered by user
          example: 201301
        message:
          type: string
          description: Message from computer
          example: 'Hi there how are you'
        word_count:
          type: integer
          description: No's of words that I have
          example: 46       

