openapi: "3.0.2"
info:
  title: Allocation Data Service
  description: This is a starter kit that can be used to create microservice
  version: "1.0.0"

servers:
  - url: https://localhost/allocation_data/v1
    description: localhost

paths:
  /{data_name}:
    post:
      tags:
        - Get Data
      description: Get the use from mobile
      operationId: controllers.data_controller.getUser
      parameters:
        - in: path
          name: data_name
          description: Data Name to be querried
          required: true
          schema:
            type: string
          example: bank_data
      requestBody:
        description: Query the database
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/query_request"

      responses:
        "200":
          description: User data
          content:
            application/json:
              schema:
                type: object

components:
  schemas:
    query_request:
      description: "Query data attributes"
      type: object
